### ISSUE TITLE
item6. 불필요한 객체 생성을 피하라

### ISSUE THREAD

**Issue by delmaSong** [TheSwiftists/effective-swift#7]
- [x] readme 수정
- [x] item6 문서 작성

### 주제
> 기존 객체를 재사용해야 한다면 새로운 객체를 만들지 마라

### 목차
- ~~불필요한 객체를 생성하는 경우~~ 하단에 작성된 상세 이유로 인해 목차 변경함
  1. 재사용 가능한 인스턴스를 매번 새롭게 생성하는 경우
    - 책에서는 자바의 String s = new String("hi"); 와 String s = "hi"; 가 별개의 인스턴스라고 하는데 Swift에서 동일하게 생성한 결과 같은 주소값을 나타냄. 그래서 적절하지 않은 예시라 판단.
![스크린샷 2020-10-31 오전 3 01 40](https://user-images.githubusercontent.com/40784518/97740997-6cead000-1b25-11eb-87cc-79cc95640f19.png)
  2. 인스턴스 생성 비용이 높은 객체를 캐시하지 않고 사용하는 경우
  3. ~~정적 초기화 후 호출하지 않는 경우~~ 
    - Swift에서 static init 사용 불가
  4. ~~적절한 타입을 사용하지 않는 경우~~ 
    - Java에선 컬렉션 타입을 감싸는? 오토박싱이란게 있어서 명시적인 컬렉션타입 사용이 아니라 오토박싱을 사용하는 것이 미미한 성능 저하를 유발한다고 함. 허나 Swift에선 엄격하게 타입을 지키도록 하고있어서 저자가 말하는 부적절한 타입(컬렉션 타입 아니라 오토박싱)을 사용하는 사례는 없는 듯.
----
- 객체를 재사용하는 게 좋은 경우
  1. 자주 사용되는 객체의 재사용
  2. 인스턴스 생성 비용이 높은 객체의 재사용
- 그렇다고 객체 생성을 피하고자 객체 풀을 만들지는 말자
- 객체 풀이란?
- 객체 풀을 사용해도 좋은 경우
- 결론

**Comment by ksundong** [comment]
Java의 boxing unboxing은 primitive type과 Wrapper type을 컴파일러가 알아서 변환해주는 것을 얘기해요.
그리고 primitive type과 Wrapper type의 메모리 관련 비용이 많이 들기 때문에 둘의 성능차이가 많이 납니다.
스위프트에서는 primitive type이라는 것이 존재하지 않기 때문에 없다고 보시면 될 것 같아요.
Java의 Collection은 짧게 말해서 자료구조를 다루는 프레임워크를 의미합니다.

help wanted가 있어서 달아봤어요! 파이팅!

**Comment by delmaSong** [comment]
@ksundong 와 감사합니다 디온! 앞으로 effective-swift의 자바 고문관으로 임명(?)합니다 🧚🏻‍♀️

**Comment by delmaSong** [comment]
해당 이슈 완료하여 클로즈합니다
