### ISSUE TITLE
item14. Comparable을 구현할지 고민하라

### ISSUE THREAD

**Issue by delmaSong** [TheSwiftists/effective-swift#8]
- [x] readme 작성
- [x] item14. 문서 작성

### Java
- Comparable 인터페이스의 `compareTo()`
  - 단순 동치성 비교에 순서까지 비교 가능
  - Comparable을 구현했다는 것은 그 클래스의 인스턴스들에는 자연적인 순서(natural order)가 있음을 뜻함
    -> swift에서는. `Equatable`, `Sequence`, `Iterator Protocol`을 다 포함한것과 비슷하려나
- `equals`

### Swift
Equatable, Comparable, 비교연산자 ===, !=== 
Hashable?

-----

### 목차
- 인트로(자바의 compareTo 소개)
- compareTo와 대응하는 Swift의 Protocol들(각각의 용도)
  - `Equatable`, `Sequence`, `Iterator Protocol`, `Comparable`, 비교연산자
- 결론(어떨 때 어떤 프로토콜을 채택할 지)

**Comment by Limwin94** [comment]
화이팅입니다!

**Comment by delmaSong** [comment]
해당 이슈 완료하여 클로즈합니다
