### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by wotjd** [TheSwiftists/effective-swift#83]
안녕하세요
실례가 될지는 모르겠지만 Github Pages 기능으로 웹에 올려주시면 어떨까하여 제안 드려봅니다.
Gitbook 으로 제너레이팅 한다면 목록별로 잘 정리되어 읽기 좋은 사이트가 생길 것 같습니다..!
올려주시는 글들은 잘 읽고 있습니다. 번역해주셔서 감사합니다 :)

**Comment by delmaSong** [comment]
안녕하세요! 좋은 제안 감사합니다. [깃헙 페이지](https://theswiftists.github.io/effective-swift/)로 만드니 읽기 훨씬 좋네요
깃북은 스터디원들과 의논하여 마련해보겠습니다 😀

**Comment by Limwin94** [comment]
안녕하세요~! 생각해보지 않았던 이슈인데 좋은 제안 주셔서 감사합니다 👍🏻

**Comment by wotjd** [comment]
갑자기 제안드려서 부담스러우셨을텐데 흔쾌히 검토해주셔서 감사합니다~! :)

**Comment by seizze** [comment]
델마가 Github Pages로 퍼블리싱하도록 처리해 주셔서 이슈 닫겠습니다~! :D
https://theswiftists.github.io/effective-swift/
